name: CI/CD Pipeline

on:
    workflow_dispatch:
# on:
#   push:
#     branches:
#       - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Test
        run: yarn test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
      - name: Deploy to S3 bucket
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ic-s3-b1
          AWS_ACCESS_KEY_ID: AKIA3ZTFVQRALWRD27V2
          AWS_SECRET_ACCESS_KEY: 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

  notify:
    needs:
      - build
      - test
      - deploy

    runs-on: ubuntu-latest
    if: always()
    steps:
    #   - name: send notification if success
    #     if: env.WORKFLOW_CONCLUSION == 'success' 
    #     uses: rtCamp/action-slack-notify@v2
    #     env:
    #         SLACK_ICON: https://github.com/rtCamp.png?size=48
    #         SLACK_CHANNEL: githubactions-poc
    #         SLACK_COLOR: ${{ job.status }}
    #         SLACK_MESSAGE: 'The pipeline Is Completed Successfully'
    #         SLACK_TITLE: React Project CI/CD
    #         SLACK_USERNAME: gaurav.talele
    #         SLACK_WEBHOOK: https://hooks.slack.com/services/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

    #   - name: send notification if failure
    #     if: ${{ env.WORKFLOW_CONCLUSION }} == 'failure' 
    #     uses: rtCamp/action-slack-notify@v2
    #     env:
    #         SLACK_ICON: https://github.com/rtCamp.png?size=48
    #         SLACK_CHANNEL: githubactions-poc
    #         SLACK_COLOR: ${{ job.status }}
    #         SLACK_MESSAGE: 'The pipeline Is NOT Completed Successfully'
    #         SLACK_TITLE: React Project CI/CD
    #         SLACK_USERNAME: gaurav.talele
    #         SLACK_WEBHOOK: https://hooks.slack.com/services/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

      - name: Send Teams notification
        uses: jdcargile/ms-teams-notification@v1.3
        if: ${{ env.WORKFLOW_CONCLUSION }} == 'success' 
        with:
            github-token: ${{ github.token }}
            ms-teams-webhook-uri: https://indigochart.webhook.office.com/webhookb2/c612a1da-d845-4af4-99df-8aa5f50c8453@7ea23193-ae2b-42c9-9252-83a6d5c5547f/IncomingWebhook/bc75a012e7e04361af09a3ab838b399c/1e7bdf5b-0e05-49d1-8047-bbddd8ef8159
            title: Deployment Sucessful
            notification-summary: The deployment of ${{ github.repository }} is Sucessful
            notification-color: 28a745

      - name: Send Teams notification
        uses: jdcargile/ms-teams-notification@v1.3
        if: ${{ env.WORKFLOW_CONCLUSION }} == 'failure' 
        with:
            github-token: ${{ github.token }}
            ms-teams-webhook-uri: https://indigochart.webhook.office.com/webhookb2/c612a1da-d845-4af4-99df-8aa5f50c8453@7ea23193-ae2b-42c9-9252-83a6d5c5547f/IncomingWebhook/bc75a012e7e04361af09a3ab838b399c/1e7bdf5b-0e05-49d1-8047-bbddd8ef8159
            title: Deployment Failed
            notification-summary: The deployment of ${{ github.repository }} is Failed
            notification-color: dc3545

    #   - name: Slack Notification
    #     uses: rtCamp/action-slack-notify@v2
    #     env:
    #       SLACK_ICON: https://github.com/rtCamp.png?size=48
    #       SLACK_CHANNEL: githubactions-poc
    #       SLACK_COLOR: ${{ job.status }}
    #       SLACK_MESSAGE: 'The pipeline Is Completed Successfully'
    #       SLACK_TITLE: React Project CI/CD
    #       SLACK_USERNAME: gaurav.talele
    #       SLACK_WEBHOOK: https://hooks.slack.com/services/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
